default: &default
  adapter: postgresql
  encoding: UTF8
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  sslmode: disable
  gssencmode: disable
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV["DATABASE_PASSWORD"].inspect %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "aic_backed_app") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME", "aic_backed_app_test") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
